image_speed = 0.5;
alarm[0] = 235;
depth = -6;
rankreview = false;
clipboardPos = 500
whiteflashAlpha = 1;
val = 0;
bgalpha = 0;
var _string = string(global.collect);
var _string_length = string_length(_string);
color_array = []
height_array = []
// cycle through array and change the colors
for (var i = 0; i < _string_length; i++)
	color_array[i] = irandom_range(1, sprite_get_width(spr_fontcollect_pal));
for (var i = 0; i < _string_length; i++)
	height_array[i] = irandom_range(-2, 0);
freezecol = { dark: [93/255, 93/255, 93/255],light: [155/255, 155/255, 155/255]}
confectiArray = ["mallow", "choco", "crack", "worm", "candy"]
targetx = 480;
playerresetbuffer = 0
palettechoose = 0
card_index = 0