var moveX = (obj_player.x + (obj_player.xscale * -30))
var moveY = (obj_player.y - 40)
var movespeed = (distance_to_point(moveX, moveY) / 200)
var d = point_direction(x, y, moveX, moveY)
hsp = lengthdir_x(((18 * movespeed) + 0.5), d)
vsp = lengthdir_y(((18 * movespeed) + 0.5), d)
x = approach(x, moveX, hsp)
y = approach(y, moveY, vsp)
if (x != obj_player.x)
    image_xscale = (-(sign((x - obj_player.x))))
if (!global.key_inv)
    instance_destroy()
